name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test-backend:
    name: Build and Test Backend Services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - user-service
          - article-service

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies for ${{ matrix.service }}
      run: |
        cd backend/${{ matrix.service }}
        npm install

    - name: Run tests for ${{ matrix.service }}
      run: |
        cd backend/${{ matrix.service }}
        npm test

  build-and-test-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install frontend dependencies
      run: |
        cd frontend/breizhsport-frontend
        npm install

    - name: Run frontend tests
      run: |
        cd frontend/breizhsport-frontend
        npm test

    - name: Build frontend
      run: |
        cd frontend/breizhsport-frontend
        npm run build

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: [build-and-test-backend, build-and-test-frontend]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to AWS (Backend Services)
      run: |
        echo "Deploying backend services..."
        # Ajouter votre script de déploiement backend ici

    - name: Deploy to AWS (Frontend)
      run: |
        echo "Deploying frontend..."
        # Ajouter votre script de déploiement frontend ici
